### ISSUE TITLE
Suggestion: Make default timeouts clearer

### ISSUE THREAD

**Issue by chucklay** [openfaas-incubator/of-watchdog#51]
Hey all,

In the documentation, `read_timeout`, `write_timeout`, and `exec_timeout` are explained, but their defaults are not mentioned. This can be a huge headache while troubleshooting as the error raised by a timeout doesn't always specify that a timeout is to blame.

## Expected Behaviour
Mention that the default timeouts are `"10s"`

## Current Behaviour
Pretty self-explanatory.

## Context
In my case, I had a faas function that took ~10s to execute. I had set the `exec_timeout` but not the `read_timeout` or `write_timeout`. My function was attempting to return, but the caller was receiving an unexplained 502 error (honestly still not sure why I was getting a 502 instead of a 408, that one might be on faas, not watchdog). It took a while to realize that a timeout might be to blame.

**Comment by alexellis** [comment]
Hi thanks for your suggestion. We'll look into this. 

> It took a while to realize that a timeout might be to blame.

This is covered in the troubleshooting guide which is prominent in the docs and it's also covered by the workshop (also in the docs) which we recommend everyone goes through. 

The timeouts can be customised, depend on different factors and are set for different parts of the project which is why you don't see an exact number front and centre in the documentation. 

Alex

**Comment by alexellis** [comment]
Derek add label: support

**Comment by alexellis** [comment]
Derek set title: Suggestion: Make default timeouts clearer

**Comment by alexellis** [comment]
Derek close: README updated
